name: Bug report
description: Template to record bug or infelicity in current code
title: "BUG: [title]"
labels:
  - bug
assignees:
  - JaimeHyland
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following fields to help us reproduce the bug.

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior. Be specific and include URLs or actions.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, error messages, or screenshots.
