name: Custom issue template
description: Describe this issue template's purpose here.
title: "Other Issue: [title]"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        *(Write your issue content here...)*
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please provide detailed information about the issue.
      placeholder: Describe the issue here...
