name: Feature request
description: Template for suggested new feature or improvement in the current app
title: "New Feature: [title]"
labels:
  - enhancement
assignees:
  - JaimeHyland
body:
  - type: textarea
    id: problem_description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives_considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
