name: Feature request
description: Template for suggested new feature or improvement in the current app
title: "New Feature: [title]"
labels:
  - enhancement
assignees:
  - JaimeHyland
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**  
        A clear and concise description of what the problem is.  
        _Ex: I'm always frustrated when [...]_

        **Describe the solution you'd like**  
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**  
        A clear and concise description of any alternative solutions or features you've considered.

        **Additional context**  
        Add any other context or screenshots about the feature request here.
