name: IDE Setup
description: This template records tasks required to set up and adapt the IDE so that the developer can create the app
title: ""
labels:
  - set-up
assignees:
  - JaimeHyland
body:
  - type: markdown
    attributes:
      value: |
        As the **Developer**, I have **set-up installed or configured** in my IDE, so that I can **benefit**.

        - CR1:  
        - CR2:
