name: User Story Template
description: This template is used to help the developer to set up User Stories on the Kanban
title: "USER STORY: [title]"
labels:
  - enhancement
assignees:
  - JaimeHyland
body:
  - type: markdown
    attributes:
      value: |
        As a **role**, I can **capability**, so that **received benefit**.

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: List the acceptance criteria for this user story
      placeholder: |
        - AC1:
        - AC2:
        - AC3:
