name: User Story Template
description: This template helps developers define and manage User Stories for the Kanban board
title: "USER STORY: [title]"
labels:
  - enhancement
assignees:
  - JaimeHyland

body:
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Describe the story using this standard format.
      value: |
        As a **[role]**, I can **[capability]**, so that **[benefit]**.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What must be true for this story to be considered complete?
      value: |
        - **AC1**: **[First acceptance condition]**
        - **AC2**: **[Second acceptance condition]**
        - **AC3**: **[Optional third condition]**

  - type: textarea
    id: notes
    attributes:
      label: Notes / Context (Optional)
      description: Add any background, links, or related discussion.
      value: |
        - [Insert relevant links or diagrams]
